$(document).ready(function(){
    $('.two').click(function(){
        $('.one').animate({
            marginLeft:'-250px'
        });
    });
    $('.three').click(function(){
        $('.one').animate({
            marginLeft:'0px'
        });
    });
});